# Generated by Django 4.2 on 2023-04-11 18:14

import db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0007_diffmaxprobhist_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPDBAlert',
            fields=[
                ('ppdbalert_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('alertsenttimestamp', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PPDBDiaForcedSource',
            fields=[
                ('ppdbdiaforcedsource_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ccdvisitid', models.BigIntegerField()),
                ('midpointtai', models.FloatField(db_index=True)),
                ('filtername', models.TextField()),
                ('psflux', models.FloatField()),
                ('psfluxerr', models.FloatField()),
                ('totflux', models.FloatField()),
                ('totfluxerr', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PPDBDiaObject',
            fields=[
                ('ppdbdiaobject_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('simversion', models.TextField(null=True)),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('mwebv', models.FloatField(null=True)),
                ('mwebv_err', models.FloatField(null=True)),
                ('z_final', models.FloatField(null=True)),
                ('z_final_err', models.FloatField(null=True)),
                ('hostgal_ellipticity', models.FloatField(null=True)),
                ('hostgal_sqradius', models.FloatField(null=True)),
                ('hostgal_zspec', models.FloatField(null=True)),
                ('hostgal_zspec_err', models.FloatField(null=True)),
                ('hostgal_zphot', models.FloatField(null=True)),
                ('hostgal_zphot_err', models.FloatField(null=True)),
                ('hostgal_zphot_q000', models.FloatField(null=True)),
                ('hostgal_zphot_q010', models.FloatField(null=True)),
                ('hostgal_zphot_q020', models.FloatField(null=True)),
                ('hostgal_zphot_q030', models.FloatField(null=True)),
                ('hostgal_zphot_q040', models.FloatField(null=True)),
                ('hostgal_zphot_q050', models.FloatField(null=True)),
                ('hostgal_zphot_q060', models.FloatField(null=True)),
                ('hostgal_zphot_q070', models.FloatField(null=True)),
                ('hostgal_zphot_q080', models.FloatField(null=True)),
                ('hostgal_zphot_q090', models.FloatField(null=True)),
                ('hostgal_zphot_q100', models.FloatField(null=True)),
                ('hostgal_zphot_p50', models.FloatField(null=True)),
                ('hostgal_mag_u', models.FloatField(null=True)),
                ('hostgal_mag_g', models.FloatField(null=True)),
                ('hostgal_mag_r', models.FloatField(null=True)),
                ('hostgal_mag_i', models.FloatField(null=True)),
                ('hostgal_mag_z', models.FloatField(null=True)),
                ('hostgal_mag_y', models.FloatField(null=True)),
                ('hostgal_ra', models.FloatField(null=True)),
                ('hostgal_dec', models.FloatField(null=True)),
                ('hostgal_snsep', models.FloatField(null=True)),
                ('hostgal_magerr_u', models.FloatField(null=True)),
                ('hostgal_magerr_g', models.FloatField(null=True)),
                ('hostgal_magerr_r', models.FloatField(null=True)),
                ('hostgal_magerr_i', models.FloatField(null=True)),
                ('hostgal_magerr_z', models.FloatField(null=True)),
                ('hostgal_magerr_y', models.FloatField(null=True)),
                ('hostgal2_ellipticity', models.FloatField(null=True)),
                ('hostgal2_sqradius', models.FloatField(null=True)),
                ('hostgal2_zspec', models.FloatField(null=True)),
                ('hostgal2_zspec_err', models.FloatField(null=True)),
                ('hostgal2_zphot', models.FloatField(null=True)),
                ('hostgal2_zphot_err', models.FloatField(null=True)),
                ('hostgal2_zphot_q000', models.FloatField(null=True)),
                ('hostgal2_zphot_q010', models.FloatField(null=True)),
                ('hostgal2_zphot_q020', models.FloatField(null=True)),
                ('hostgal2_zphot_q030', models.FloatField(null=True)),
                ('hostgal2_zphot_q040', models.FloatField(null=True)),
                ('hostgal2_zphot_q050', models.FloatField(null=True)),
                ('hostgal2_zphot_q060', models.FloatField(null=True)),
                ('hostgal2_zphot_q070', models.FloatField(null=True)),
                ('hostgal2_zphot_q080', models.FloatField(null=True)),
                ('hostgal2_zphot_q090', models.FloatField(null=True)),
                ('hostgal2_zphot_q100', models.FloatField(null=True)),
                ('hostgal2_zphot_p50', models.FloatField(null=True)),
                ('hostgal2_mag_u', models.FloatField(null=True)),
                ('hostgal2_mag_g', models.FloatField(null=True)),
                ('hostgal2_mag_r', models.FloatField(null=True)),
                ('hostgal2_mag_i', models.FloatField(null=True)),
                ('hostgal2_mag_z', models.FloatField(null=True)),
                ('hostgal2_mag_y', models.FloatField(null=True)),
                ('hostgal2_ra', models.FloatField(null=True)),
                ('hostgal2_dec', models.FloatField(null=True)),
                ('hostgal2_snsep', models.FloatField(null=True)),
                ('hostgal2_magerr_u', models.FloatField(null=True)),
                ('hostgal2_magerr_g', models.FloatField(null=True)),
                ('hostgal2_magerr_r', models.FloatField(null=True)),
                ('hostgal2_magerr_i', models.FloatField(null=True)),
                ('hostgal2_magerr_z', models.FloatField(null=True)),
                ('hostgal2_magerr_y', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPDBDiaSource',
            fields=[
                ('ppdbdiasource_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ccdvisitid', models.BigIntegerField()),
                ('parent_ppdbdiasource_id', models.BigIntegerField(null=True)),
                ('midpointtai', models.FloatField(db_index=True)),
                ('filtername', models.TextField()),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('psflux', models.FloatField()),
                ('psfluxerr', models.FloatField()),
                ('snr', models.FloatField()),
                ('nobs', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diaalert',
            name='diaObject',
        ),
        migrations.RemoveField(
            model_name='diaalert',
            name='diaSource',
        ),
        migrations.RemoveConstraint(
            model_name='brokerclassification',
            name='unique_constarint_elasticc2_brokerclassification_partitionkey',
        ),
        migrations.RemoveIndex(
            model_name='brokerclassifier',
            name='elasticc2_b_brokerN_f8074f_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokerclassifier',
            name='elasticc2_b_brokerN_eb327f_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokerclassifier',
            name='elasticc2_b_brokerN_57d6c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokerclassifier',
            name='elasticc2_b_brokerN_bfc520_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokermessage',
            name='elasticc2_b_topicNa_1b0625_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokermessage',
            name='elasticc2_b_alertId_547cdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokermessage',
            name='elasticc2_b_diaSour_d86ee7_idx',
        ),
        migrations.RemoveIndex(
            model_name='diaobject',
            name='idx_elasticc2_diaobject_q3c',
        ),
        migrations.RemoveIndex(
            model_name='diasource',
            name='idx_elasticc2_diasource_q3c',
        ),
        migrations.RenameField(
            model_name='brokerclassification',
            old_name='classId',
            new_name='classid',
        ),
        migrations.RenameField(
            model_name='brokerclassification',
            old_name='classificationId',
            new_name='classification_id',
        ),
        migrations.RenameField(
            model_name='brokerclassification',
            old_name='classifierId',
            new_name='classifier_id',
        ),
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='brokerName',
            new_name='brokername',
        ),
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='brokerVersion',
            new_name='brokerversion',
        ),
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='classifierId',
            new_name='classifier_id',
        ),
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='classifierName',
            new_name='classifiername',
        ),
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='classifierParams',
            new_name='classifierparams',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='alertId',
            new_name='alert_id',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='brokerIngestTimestamp',
            new_name='brokeringesttimestamp',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='brokerMessageId',
            new_name='brokermessage_id',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='descIngestTimestamp',
            new_name='descingesttimestamp',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='diaSourceId',
            new_name='diasource_id',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='elasticcPublishTimestamp',
            new_name='elasticcpublishtimestamp',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='msgHdrTimestamp',
            new_name='msghdrtimestamp',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='streamMessageId',
            new_name='streammessage_id',
        ),
        migrations.RenameField(
            model_name='brokermessage',
            old_name='topicName',
            new_name='topicname',
        ),
        migrations.RenameField(
            model_name='classidofgentype',
            old_name='classId',
            new_name='classid',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='ccdVisitId',
            new_name='ccdvisitid',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='diaForcedSourceId',
            new_name='diaforcedsource_id',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='filterName',
            new_name='filtername',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='midPointTai',
            new_name='midpointtai',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='psFlux',
            new_name='psflux',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='psFluxErr',
            new_name='psfluxerr',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='totFlux',
            new_name='totflux',
        ),
        migrations.RenameField(
            model_name='diaforcedsource',
            old_name='totFluxErr',
            new_name='totfluxerr',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='diaObjectId',
            new_name='diaobject_id',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_mag_Y',
            new_name='hostgal2_mag_y',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_magerr_Y',
            new_name='hostgal2_magerr_y',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_mag_Y',
            new_name='hostgal_mag_y',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_magerr_Y',
            new_name='hostgal_magerr_y',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='simVersion',
            new_name='simversion',
        ),
        migrations.RenameField(
            model_name='diaobjecttruth',
            old_name='peakmag_Y',
            new_name='peakmag_y',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='ccdVisitId',
            new_name='ccdvisitid',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='diaSourceId',
            new_name='diasource_id',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='filterName',
            new_name='filtername',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='midPointTai',
            new_name='midpointtai',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='parentDiaSourceId',
            new_name='parent_diasource_id',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='psFlux',
            new_name='psflux',
        ),
        migrations.RenameField(
            model_name='diasource',
            old_name='psFluxErr',
            new_name='psfluxerr',
        ),
        migrations.RenameField(
            model_name='diatruth',
            old_name='diaObjectId',
            new_name='ppdbdiaobject_id',
        ),
        migrations.RenameField(
            model_name='diatruth',
            old_name='diaSourceId',
            new_name='ppdbdiasource_id',
        ),
        migrations.RenameField(
            model_name='gentypeofclassid',
            old_name='classId',
            new_name='classid',
        ),
        migrations.RemoveField(
            model_name='brokerclassification',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='diaforcedsource',
            name='diaObject',
        ),
        migrations.RemoveField(
            model_name='diaobjectoftarget',
            name='diaObject',
        ),
        migrations.RemoveField(
            model_name='diaobjecttruth',
            name='diaObject',
        ),
        migrations.RemoveField(
            model_name='diasource',
            name='diaObject',
        ),
        migrations.AlterField(
            model_name='brokerclassification',
            name='dbMessage',
            field=models.ForeignKey(db_column='brokermessage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.brokermessage'),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokername'], name='elasticc2_b_brokern_de7788_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokername', 'brokerversion'], name='elasticc2_b_brokern_7aa2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokername', 'classifiername'], name='elasticc2_b_brokern_177700_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokername', 'brokerversion', 'classifiername', 'classifierparams'], name='elasticc2_b_brokern_fad924_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['topicname', 'streammessage_id'], name='elasticc2_b_topicna_1d46af_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['alert_id'], name='elasticc2_b_alert_i_e54f19_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['diasource_id'], name='elasticc2_b_diasour_48b2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='diaobject',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'decl'), name='idx_elasticc2_diaobject_q3c'),
        ),
        migrations.AddIndex(
            model_name='diasource',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'decl'), name='idx_elasticc2_diasource_q3c'),
        ),
        migrations.AddConstraint(
            model_name='brokerclassification',
            constraint=models.UniqueConstraint(fields=('classifier_id', 'classification_id'), name='unique_constarint_elasticc2_brokerclassification_partitionkey'),
        ),
        migrations.DeleteModel(
            name='DiaAlert',
        ),
        migrations.AddField(
            model_name='ppdbdiasource',
            name='ppdbdiaobject',
            field=models.ForeignKey(db_column='ppdbdiaobject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
        ),
        migrations.AddIndex(
            model_name='ppdbdiaobject',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'decl'), name='idx_elasticc2_ppdbdiaobject_q3c'),
        ),
        migrations.AddField(
            model_name='ppdbdiaforcedsource',
            name='ppdbdiaobject',
            field=models.ForeignKey(db_column='ppdbdiaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
        ),
        migrations.AddField(
            model_name='ppdbalert',
            name='ppdbdiaobject',
            field=models.ForeignKey(db_column='ppdbdiaobject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
        ),
        migrations.AddField(
            model_name='ppdbalert',
            name='ppdbdiasource',
            field=models.ForeignKey(db_column='ppdbdiasource_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiasource'),
        ),
        migrations.AddField(
            model_name='diaforcedsource',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaobjectoftarget',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaobjecttruth',
            name='ppdbdiaobject',
            field=models.OneToOneField(db_column='ppdbdiaobject_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elasticc2.ppdbdiaobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diasource',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject'),
        ),
        migrations.AddIndex(
            model_name='ppdbdiasource',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'decl'), name='idx_elasticc2_ppdbdiasource_q3c'),
        ),
    ]
