# Generated by Django 4.2 on 2023-04-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0008_refactor_elasticc2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaTruth',
        ),
        migrations.RemoveField(
            model_name='diaobject',
            name='hostgal2_zphot_p50',
        ),
        migrations.RemoveField(
            model_name='diaobject',
            name='hostgal_zphot_p50',
        ),
        migrations.RemoveField(
            model_name='ppdbdiaobject',
            name='hostgal2_zphot_p50',
        ),
        migrations.RemoveField(
            model_name='ppdbdiaobject',
            name='hostgal_zphot_p50',
        ),
    ]
