# Generated by Django 4.2 on 2023-05-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0011_rename_dbmessage_brokerclassification_dbmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaforcedsource',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject'),
        ),
    ]
