# Generated by Django 4.2.2 on 2023-06-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0012_alter_diaforcedsource_diaobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppdbalert',
            old_name='ppdbalert_id',
            new_name='alert_id',
        ),
        migrations.RenameField(
            model_name='ppdbdiaforcedsource',
            old_name='ppdbdiaforcedsource_id',
            new_name='diaforcedsource_id',
        ),
        migrations.RenameField(
            model_name='ppdbdiaobject',
            old_name='ppdbdiaobject_id',
            new_name='diaobject_id',
        ),
        migrations.RenameField(
            model_name='ppdbdiasource',
            old_name='ppdbdiasource_id',
            new_name='diasource_id',
        ),
        migrations.RemoveField(
            model_name='diaobjecttruth',
            name='ppdbdiaobject',
        ),
        migrations.RemoveField(
            model_name='ppdbalert',
            name='ppdbdiaobject',
        ),
        migrations.RemoveField(
            model_name='ppdbalert',
            name='ppdbdiasource',
        ),
        migrations.RemoveField(
            model_name='ppdbdiaforcedsource',
            name='ppdbdiaobject',
        ),
        migrations.RemoveField(
            model_name='ppdbdiasource',
            name='ppdbdiaobject',
        ),
        migrations.AddField(
            model_name='diaobjecttruth',
            name='diaobject',
            field=models.OneToOneField(db_column='diaobject_id', default=5, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elasticc2.ppdbdiaobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppdbalert',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
        ),
        migrations.AddField(
            model_name='ppdbalert',
            name='diasource',
            field=models.ForeignKey(db_column='diasource_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiasource'),
        ),
        migrations.AddField(
            model_name='ppdbdiaforcedsource',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', default=5, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppdbdiasource',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc2.ppdbdiaobject'),
        ),
    ]
