# Generated by Django 4.2.2 on 2023-06-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0013_rename_ppdbalert_id_ppdbalert_alert_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaobjecttruth',
            name='galnmatch',
        ),
    ]
