# Generated by Django 4.2.2 on 2023-06-08 17:29

from django.db import migrations


def populate_classidofgentype( apps, schema_editor ):
    CMap = apps.get_model( 'elasticc2', 'GentypeOfClassId' )
    CMap.objects.all().delete()

    cmap = CMap( gentype=None, classid=0, description='Meta' )
    cmap.save()
    cmap = CMap( gentype=None, classid=100, description='Meta/Other' )
    cmap.save()
    cmap = CMap( gentype=None, classid=200, description='Residual' )
    cmap.save()
    cmap = CMap( gentype=None, classid=300, description='NotClassified' )
    cmap.save()
    cmap = CMap( gentype=None, classid=1000, description='Static' )
    cmap.save()
    cmap = CMap( gentype=None, classid=1100, description='Static/Other' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2000, description='Variable' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2100, description='Variable/Other' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2200, description='Non-Recurring' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2210, description='Non-Recurring/Other' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2220, description='SN-like' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2221, description='SN-like/Other' )
    cmap.save()
    cmap = CMap( gentype=10, classid=2222, description='Ia' )
    cmap.save()
    cmap = CMap( gentype=20, classid=2223, description='Ib/c' )
    cmap.save()
    cmap = CMap( gentype=21, classid=2223, description='Ib/c' )
    cmap.save()
    cmap = CMap( gentype=25, classid=2223, description='Ib/c' )
    cmap.save()
    cmap = CMap( gentype=26, classid=2223, description='Ib/c' )
    cmap.save()
    cmap = CMap( gentype=27, classid=2223, description='Ib/c' )
    cmap.save()
    cmap = CMap( gentype=30, classid=2224, description='II' )
    cmap.save()
    cmap = CMap( gentype=31, classid=2224, description='II' )
    cmap.save()
    cmap = CMap( gentype=32, classid=2224, description='II' )
    cmap.save()
    cmap = CMap( gentype=35, classid=2224, description='II' )
    cmap.save()
    cmap = CMap( gentype=36, classid=2224, description='II' )
    cmap.save()
    cmap = CMap( gentype=37, classid=2224, description='II' )
    cmap.save()
    cmap = CMap( gentype=12, classid=2225, description='Iax' )
    cmap.save()
    cmap = CMap( gentype=11, classid=2226, description='91bg' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2230, description='Fast' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2231, description='Fast/Other' )
    cmap.save()
    cmap = CMap( gentype=50, classid=2232, description='KN' )
    cmap.save()
    cmap = CMap( gentype=51, classid=2232, description='KN' )
    cmap.save()
    cmap = CMap( gentype=82, classid=2233, description='M-dwarf Flare' )
    cmap.save()
    cmap = CMap( gentype=84, classid=2234, description='Dwarf Novae' )
    cmap.save()
    cmap = CMap( gentype=87, classid=2235, description='uLens' )
    cmap.save()
    cmap = CMap( gentype=88, classid=2235, description='uLens' )
    cmap.save()
    cmap = CMap( gentype=89, classid=2235, description='uLens' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2240, description='Long' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2241, description='Long/Other' )
    cmap.save()
    cmap = CMap( gentype=40, classid=2242, description='SLSN' )
    cmap.save()
    cmap = CMap( gentype=42, classid=2243, description='TDE' )
    cmap.save()
    cmap = CMap( gentype=45, classid=2244, description='ILOT' )
    cmap.save()
    cmap = CMap( gentype=46, classid=2245, description='CART' )
    cmap.save()
    cmap = CMap( gentype=59, classid=2246, description='PISN' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2300, description='Recurring' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2310, description='Recurring/Other' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2320, description='Periodic' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2321, description='Periodic/Other' )
    cmap.save()
    cmap = CMap( gentype=90, classid=2322, description='Cepheid' )
    cmap.save()
    cmap = CMap( gentype=80, classid=2323, description='RR Lyrae' )
    cmap.save()
    cmap = CMap( gentype=91, classid=2324, description='Delta Scuti' )
    cmap.save()
    cmap = CMap( gentype=83, classid=2325, description='EB' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2326, description='LPV/Mira' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2330, description='Non-Periodic' )
    cmap.save()
    cmap = CMap( gentype=None, classid=2331, description='Non-Periodic/Other' )
    cmap.save()
    cmap = CMap( gentype=60, classid=2332, description='AGN' )
    cmap.save()

def populate_gentypeofclassid( apps, schema_editor ):
    CMap = apps.get_model( "elasticc2", "ClassIdOfGentype" )
    CMap.objects.all().delete()

    for gentype in [ 10, 11, 12, 20, 21, 25, 26, 27, 30, 31, 32, 35, 36,
                     37, 40, 42, 45, 46, 50, 51, 59, 60, 80, 82, 83, 84,
                     87, 88, 89, 90, 91 ]:
    
        cmap = CMap( classid=2000, gentype=gentype, description='Variable',
                     exactmatch=False, categorymatch=False, generalmatch=False, broadmatch=True )
        cmap.save()
    
    for gentype in [ 10, 11, 12, 20, 21, 25, 26, 27, 30, 31, 32, 35, 36,
                     37, 40, 42, 45, 46, 50, 51, 59, 82, 84, 87, 88, 89
                    ]:
        cmap = CMap( classid=2200, gentype=gentype, description='Non-Recurring',
                     exactmatch=False, categorymatch=False, generalmatch=True, broadmatch=True )
        cmap.save()

    for gentype in [ 10, 11, 12, 20, 21, 25, 26, 27, 30, 31, 32, 35, 36, 37 ]:
        cmap = CMap( classid=2220, gentype=gentype, description='SN-like',
                     exactmatch=False, categorymatch=True, generalmatch=True, broadmatch=True )
        cmap.save()

    cmap = CMap( gentype=10, classid=2222, description='Ia',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=11, classid=2226, description='91bg',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=12, classid=2225, description='Iax',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=20, classid=2223, description='Ib/c',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=21, classid=2223, description='Ib/c',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=25, classid=2223, description='Ib/c',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=26, classid=2223, description='Ib/c',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=27, classid=2223, description='Ib/c',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=30, classid=2224, description='II',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=31, classid=2224, description='II',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=32, classid=2224, description='II',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=35, classid=2224, description='II',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=36, classid=2224, description='II',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=37, classid=2224, description='II',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    
    for gentype in [ 50, 51, 82, 84, 87, 88, 89 ]:
        cmap = CMap( classid=2230, gentype=gentype, description='Fast',
                     exactmatch=False, categorymatch=True, generalmatch=True, broadmatch=True )
        cmap.save()

    cmap = CMap( gentype=50, classid=2232, description='KN',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=51, classid=2232, description='KN',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=82, classid=2233, description='M-dwarf Flare',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=84, classid=2234, description='Dwarf Novae',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=87, classid=2235, description='uLens',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=88, classid=2235, description='uLens',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=89, classid=2235, description='uLens',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()

    for gentype in [ 40, 42, 45, 46, 59 ]:
        cmap = CMap( classid=2240, gentype=gentype, description='Long',
                     exactmatch=False, categorymatch=True, generalmatch=True, broadmatch=True )
        cmap.save()

    cmap = CMap( gentype=40, classid=2242, description='SLSN',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=42, classid=2243, description='TDE',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=45, classid=2244, description='ILOT',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=46, classid=2245, description='CART',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=59, classid=2246, description='PISN',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()

    for gentype in [ 60, 80, 83, 90, 91 ]:
        cmap = CMap( classid=2300, gentype=gentype, description='Recurring',
                     exactmatch=False, categorymatch=False, generalmatch=True, broadmatch=True )
        cmap.save()

    for gentype in [ 80, 83, 90, 91 ]:
        cmap = CMap( classid=2320, gentype=gentype, description='Periodic',
                     exactmatch=False, categorymatch=True, generalmatch=True, broadmatch=True )
        cmap.save()

    cmap = CMap( gentype=90, classid=2322, description='Cepheid',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=80, classid=2323, description='RR Lyrae',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=91, classid=2324, description='Delta Scuti',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()
    cmap = CMap( gentype=83, classid=2325, description='EB',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()

    for gentype in [ 60 ]:
        cmap = CMap( classid=2330, gentype=gentype, description='Non-Periodic',
                     exactmatch=False, categorymatch=True, generalmatch=True, broadmatch=True )
        cmap.save()

    cmap = CMap( gentype=60, classid=2332, description='AGN',
                 exactmatch=True, categorymatch=True, generalmatch=True, broadmatch=True )
    cmap.save()



class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0015_classidofgentype_broadmatch_and_more'),
    ]

    operations = [
        migrations.RunPython( populate_classidofgentype ),
        migrations.RunPython( populate_gentypeofclassid )
    ]
