# Generated by Django 4.1.7 on 2023-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0017_trainingalert_trainingdiaforcedsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSourceIds',
            fields=[
                ('diasource_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportPPDBRunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
            ],
        ),
    ]
