# Generated by Django 4.2.4 on 2023-08-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0020_diaobject_isddf_ppdbdiaobject_isddf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassBrokerMessage',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
    ]
