# Generated by Django 4.2.6 on 2023-10-18 20:48

import db.models
import django.contrib.postgres.fields
from django.db import migrations, models
import psqlextra.backend.migrations.operations.delete_partitioned_model


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0021_alter_brokerclassification_probability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassBrokerMessageBySource',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CassBrokerMessageByTime',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='brokerclassification',
            name='dbmessage',
        ),
        migrations.DeleteModel(
            name='CassBrokerMessage',
        ),
        migrations.RemoveIndex(
            model_name='brokermessage',
            name='elasticc2_b_topicna_1d46af_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokermessage',
            name='elasticc2_b_alert_i_e54f19_idx',
        ),
        migrations.RemoveIndex(
            model_name='brokermessage',
            name='elasticc2_b_diasour_48b2d5_idx',
        ),
        migrations.RemoveField(
            model_name='brokermessage',
            name='modified',
        ),
        migrations.AddField(
            model_name='brokermessage',
            name='classid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='brokermessage',
            name='classifier_id',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokermessage',
            name='probability',
            field=django.contrib.postgres.fields.ArrayField(base_field=db.models.Float32Field(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='brokermessage',
            name='alert_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='brokermessage',
            name='descingesttimestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='brokermessage',
            name='diasource_id',
            field=models.BigIntegerField(db_index=True),
        ),
        psqlextra.backend.migrations.operations.delete_partitioned_model.PostgresDeletePartitionedModel(
            name='BrokerClassification',
        ),
    ]
