# Generated by Django 4.2.7 on 2024-01-23 20:06

import db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0022_cassbrokermessagebysource_cassbrokermessagebytime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaObjectClassification',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latestclass1id', models.SmallIntegerField()),
                ('latestclass2id', models.SmallIntegerField(null=True)),
                ('latestclass3id', models.SmallIntegerField(null=True)),
                ('latestclass4id', models.SmallIntegerField(null=True)),
                ('latestclass1prob', db.models.Float32Field()),
                ('latestclass2prob', db.models.Float32Field(null=True)),
                ('latestclass3prob', db.models.Float32Field(null=True)),
                ('latestclass4prob', db.models.Float32Field(null=True)),
                ('classifier', models.ForeignKey(db_column='classifier_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.brokerclassifier')),
            ],
        ),
        migrations.CreateModel(
            name='DiaObjectInfo',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filtername', models.TextField(db_index=True)),
                ('firstsource_id', models.BigIntegerField(db_index=True, null=True)),
                ('firstsourceflux', models.FloatField(null=True)),
                ('firstsourcefluxerr', models.FloatField(null=True)),
                ('firstsourcemjd', models.FloatField(db_index=True, null=True)),
                ('maxforcedsource_id', models.BigIntegerField(db_index=True, null=True)),
                ('maxforcedsourceflux', models.FloatField(null=True)),
                ('maxforcedsourcefluxerr', models.FloatField(null=True)),
                ('maxforcedsourceflux_mjd', models.FloatField(db_index=True, null=True)),
                ('latestsource_id', models.BigIntegerField(db_index=True, null=True)),
                ('latestsourceflux', models.FloatField(null=True)),
                ('latestsourcefluxerr', models.FloatField(null=True)),
                ('latestsourceflux_mjd', models.FloatField(db_index=True, null=True)),
                ('latestforcedsource_id', models.BigIntegerField(db_index=True, null=True)),
                ('latestforcedsourceflux', models.FloatField(null=True)),
                ('latestforcedsourcefluxerr', models.FloatField(null=True)),
                ('latestforcedsourceflux_mjd', models.FloatField(db_index=True, null=True)),
                ('diaobject', models.OneToOneField(db_column='diaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject')),
            ],
        ),
        migrations.DeleteModel(
            name='CassBrokerMessageByTime',
        ),
        migrations.AddField(
            model_name='diaobjectclassification',
            name='diaobject',
            field=models.ForeignKey(db_column='diaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobjectinfo'),
        ),
        migrations.AddConstraint(
            model_name='diaobjectinfo',
            constraint=models.UniqueConstraint(fields=('diaobject_id', 'filtername'), name='diaobjectinfo_unique'),
        ),
        migrations.AddConstraint(
            model_name='diaobjectclassification',
            constraint=models.UniqueConstraint(fields=('diaobject_id', 'classifier_id'), name='diaobjectclassification_unique'),
        ),
    ]
