# Generated by Django 4.2.7 on 2024-01-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0024_alter_diaobjectinfo_diaobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaobjectinfo',
            old_name='latestforcedsourceflux_mjd',
            new_name='latestforcedsourcemjd',
        ),
        migrations.RenameField(
            model_name='diaobjectinfo',
            old_name='latestsourceflux_mjd',
            new_name='latestsourcemjd',
        ),
        migrations.RenameField(
            model_name='diaobjectinfo',
            old_name='maxforcedsourceflux_mjd',
            new_name='maxforcedsourcemjd',
        ),
    ]
