# Generated by Django 4.2.7 on 2024-03-27 14:40

import db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elasticc2', '0025_rename_latestforcedsourceflux_mjd_diaobjectinfo_latestforcedsourcemjd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedSpectra',
            fields=[
                ('wantspec_id', models.TextField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('wanttime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('requester', models.TextField(null=True)),
                ('priority', models.IntegerField()),
                ('diaobject', models.ForeignKey(db_column='diaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpectrumInfo',
            fields=[
                ('specinfo_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('facility', models.TextField(null=True)),
                ('inserted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mjd', db.models.Float32Field(db_index=True)),
                ('z', db.models.Float32Field(null=True)),
                ('classid', models.IntegerField(db_index=True, null=True)),
                ('diaobject', models.ForeignKey(db_column='diaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedSpectra',
            fields=[
                ('reqspec_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('facility', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plantime', models.DateTimeField(null=True)),
                ('comment', models.TextField(default='')),
                ('diaobject', models.ForeignKey(db_column='diaobject_id', on_delete=django.db.models.deletion.CASCADE, to='elasticc2.diaobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
