# Generated by Django 4.2.16 on 2025-01-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0026_wantedspectra_spectruminfo_plannedspectra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CassBrokerMessageBySource',
        ),
    ]
