# Generated by Django 4.2.7 on 2024-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc2', '0026_wantedspectra_spectruminfo_requestedspectra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedspectra',
            name='wantspec_id',
            field=models.TextField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
