THIS NEEDS TO BE UPDATED, MANY THINGS HERE ARE WRONG

apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    field.cattle.io/creatorId: u-6fc5nwq2ou
    nersc.gov/collab_uids: 70268,99896
    nersc.gov/gid: "95089"
    nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,74560,92576,94721,95089,96414,99650
    nersc.gov/roles: user
    nersc.gov/uid: "95089"
    nersc.gov/username: raknop
  creationTimestamp: "2022-11-08T17:38:58Z"
  labels:
    cattle.io/creator: norman
  name: tom-desc-diagnosticupdate
  namespace: desc-tom
  resourceVersion: "425251230"
  selfLink: /apis/batch/v1/namespaces/desc-tom/cronjobs/tom-desc-diagnosticupdate
  uid: 45615d7a-17d3-434f-afb9-f99c752cf5d7
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            cattle.io/timestamp: "2022-11-08T18:28:05Z"
            field.cattle.io/ports: '[[]]'
            nersc.gov/collab_uids: 70268,99896
            nersc.gov/gid: "95089"
            nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,74560,92576,94721,95089,96414,99650
            nersc.gov/roles: user
            nersc.gov/uid: "95089"
            nersc.gov/username: raknop
          creationTimestamp: null
        spec:
          containers:
          - command:
            - bash
            - /tom_desc/scripts/run_diagnostics.sh
            env:
            - name: DB_HOST
              value: tom-desc-postgres
            - name: DB_NAME
              value: tom_desc
            - name: DB_PASS
              value: fragile
            - name: DB_USER
              value: postgres
            image: registry.nersc.gov/m1727/raknop/tom_server_bindmount
            imagePullPolicy: Always
            name: tom-desc-diagnosticupdate
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 95089
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /secrets
              name: desc-tom-secrets
            - mountPath: /tom_desc
              name: tom-deploy-production
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 60152
          terminationGracePeriodSeconds: 30
          volumes:
          - name: desc-tom-secrets
            secret:
              defaultMode: 256
              optional: false
              secretName: desc-tom-secrets
          - hostPath:
              path: /global/cfs/cdirs/desc-td/SOFTWARE/tom_deployment/production/tom_desc
              type: Directory
            name: tom-deploy-production
  schedule: 30 18 * * *
  successfulJobsHistoryLimit: 3
  suspend: true
status:
  lastScheduleTime: "2023-02-27T18:30:00Z"
