apiVersion: batch/v1
kind: CronJob
metadata:
  name: tom-send-alerts
  namespace: desc-tom
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            field.cattle.io/ports: '[[]]'
            nersc.gov/collab_uids: "99896"
            nersc.gov/gid: "95089"
            nersc.gov/gids: 95089,57177,60152,96414
            nersc.gov/roles: user
            nersc.gov/uid: "95089"
            nersc.gov/username: raknop
          creationTimestamp: null
        spec:
          containers:
          - command: ['python']
            args: ['manage.py', 'send_elasticc2_alerts',
               '-a', '36',
               '-k', 'public.alerts.ztf.uw.edu:9092', '-t', 'elasticc-1',
               '--do'
                  ]
            env:
            - name: DB_HOST
              value: tom-desc-postgres
            - name: DB_NAME
              value: tom_desc
            - name: DB_PASS
              value: fragile
            - name: DB_USER
              value: postgres
            image: rknop/tom-desc-production
            imagePullPolicy: Always
            name: tom-2-send-alerts
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 95089
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /secrets
              name: tom-secrets
            - mountPath: /tom_desc
              name: tom-deployment
            workingDir: /tom_desc
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 57177
          terminationGracePeriodSeconds: 30
          volumes:
          - name: tom-secrets
            secret:
              defaultMode: 256
              optional: false
              secretName: tom-secrets
          - hostPath:
              path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/production/tom_desc/tom_desc
              type: Directory
            name: tom-deployment
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 7
  suspend: false
