# Generated by Django 4.2.16 on 2024-12-05 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fastdb_dev', '0004_partitioning_v1_1b'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfstopvtoss',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diaforcedsource',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diasource',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dstopvtoss',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
