version: "3"
services:
  tom:
    build: .
    ports:
      - "8080:8080"
    entrypoint:
      - "./scripts/wait-for-it.sh"
      - "postgres:5432"
      - "--"
      - "./scripts/docker-entrypoint.sh"
    depends_on:
      - "postgres"
    volumes:
      - .:/tom_desc
    environment:
      - DJANGO_SECRET_KEY=secret
      - DJANGO_SUPERUSER_PASSWORD=password
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres

