version: "3.2"
services:
  tom:
    build: .
    ports:
      - "8080:8080"
    entrypoint:
      - "./scripts/wait-for-it.sh"
      - "postgres:5432"
      - "--"
      - "./scripts/docker-entrypoint.sh"
    depends_on:
      - "postgres"
    volumes:
      - type: bind
        source: /home/rknop/research/desc/tom_desc
        target: /tom_desc
    environment:
      - DJANGO_SECRET_KEY=secret
      - DJANGO_SUPERUSER_PASSWORD=password
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - GOOGLE_CLOUD_PROJECT=pitt-broker-user-project
      - GOOGLE_APPLICATION_CREDENTIALS=GCP_auth_key-pitt_broker_user_project.json
    user: "1000:1000"
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
