# Generated by Django 3.2.11 on 2022-03-28 14:25

from django.db import migrations, models
import django.db.models.deletion
import elasticc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerClassification',
            fields=[
                ('dbClassificationIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('classId', models.IntegerField()),
                ('probability', models.FloatField()),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerClassifier',
            fields=[
                ('dbClassifierIndex', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('brokerName', models.CharField(max_length=100)),
                ('brokerVersion', models.TextField(null=True)),
                ('classiferName', models.CharField(max_length=200)),
                ('classifierParams', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerMessage',
            fields=[
                ('dbMessageIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('streamMessageId', models.BigIntegerField(null=True)),
                ('topicName', models.CharField(max_length=200)),
                ('alertId', models.BigIntegerField()),
                ('diaSourceId', models.BigIntegerField()),
                ('descIngestTimestamp', models.DateTimeField(auto_now_add=True)),
                ('elasticcPublishTimestamp', models.DateTimeField(null=True)),
                ('brokerIngestTimestamp', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaAlert',
            fields=[
                ('alertId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaAlertPrvForcedSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiaAlertPrvSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiaForcedSource',
            fields=[
                ('diaForcedSourceId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ccdVisitId', models.BigIntegerField()),
                ('midPointTai', models.FloatField()),
                ('filterName', models.TextField()),
                ('psFlux', models.FloatField()),
                ('psFluxErr', models.FloatField()),
                ('totFlux', models.FloatField()),
                ('totFluxErr', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiaObject',
            fields=[
                ('diaObjectId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('mwebv', models.FloatField(null=True)),
                ('mwebv_err', models.FloatField(null=True)),
                ('z_final', models.FloatField(null=True)),
                ('z_final_err', models.FloatField(null=True)),
                ('hostgal_ellipticity', models.FloatField(null=True)),
                ('hostgal_sqradius', models.FloatField(null=True)),
                ('hostgal_z', models.FloatField(null=True)),
                ('hostgal_z_err', models.FloatField(null=True)),
                ('hostgal_zphot_q10', models.FloatField(null=True)),
                ('hostgal_zphot_q20', models.FloatField(null=True)),
                ('hostgal_zphot_q30', models.FloatField(null=True)),
                ('hostgal_zphot_q40', models.FloatField(null=True)),
                ('hostgal_zphot_q50', models.FloatField(null=True)),
                ('hostgal_zphot_q60', models.FloatField(null=True)),
                ('hostgal_zphot_q70', models.FloatField(null=True)),
                ('hostgal_zphot_q80', models.FloatField(null=True)),
                ('hostgal_zphot_q90', models.FloatField(null=True)),
                ('hostgal_zphot_q99', models.FloatField(null=True)),
                ('hostgal_mag_u', models.FloatField(null=True)),
                ('hostgal_mag_g', models.FloatField(null=True)),
                ('hostgal_mag_r', models.FloatField(null=True)),
                ('hostgal_mag_i', models.FloatField(null=True)),
                ('hostgal_mag_z', models.FloatField(null=True)),
                ('hostgal_mag_Y', models.FloatField(null=True)),
                ('hostgal_ra', models.FloatField(null=True)),
                ('hostgal_dec', models.FloatField(null=True)),
                ('hostgal_snsep', models.FloatField(null=True)),
                ('hostgal_magerr_u', models.FloatField(null=True)),
                ('hostgal_magerr_g', models.FloatField(null=True)),
                ('hostgal_magerr_r', models.FloatField(null=True)),
                ('hostgal_magerr_i', models.FloatField(null=True)),
                ('hostgal_magerr_z', models.FloatField(null=True)),
                ('hostgal_magerr_Y', models.FloatField(null=True)),
                ('hostgal2_ellipticity', models.FloatField(null=True)),
                ('hostgal2_sqradius', models.FloatField(null=True)),
                ('hostgal2_z', models.FloatField(null=True)),
                ('hostgal2_z_err', models.FloatField(null=True)),
                ('hostgal2_zphot_q10', models.FloatField(null=True)),
                ('hostgal2_zphot_q20', models.FloatField(null=True)),
                ('hostgal2_zphot_q30', models.FloatField(null=True)),
                ('hostgal2_zphot_q40', models.FloatField(null=True)),
                ('hostgal2_zphot_q50', models.FloatField(null=True)),
                ('hostgal2_zphot_q60', models.FloatField(null=True)),
                ('hostgal2_zphot_q70', models.FloatField(null=True)),
                ('hostgal2_zphot_q80', models.FloatField(null=True)),
                ('hostgal2_zphot_q90', models.FloatField(null=True)),
                ('hostgal2_zphot_q99', models.FloatField(null=True)),
                ('hostgal2_mag_u', models.FloatField(null=True)),
                ('hostgal2_mag_g', models.FloatField(null=True)),
                ('hostgal2_mag_r', models.FloatField(null=True)),
                ('hostgal2_mag_i', models.FloatField(null=True)),
                ('hostgal2_mag_z', models.FloatField(null=True)),
                ('hostgal2_mag_Y', models.FloatField(null=True)),
                ('hostgal2_ra', models.FloatField(null=True)),
                ('hostgal2_dec', models.FloatField(null=True)),
                ('hostgal2_snsep', models.FloatField(null=True)),
                ('hostgal2_magerr_u', models.FloatField(null=True)),
                ('hostgal2_magerr_g', models.FloatField(null=True)),
                ('hostgal2_magerr_r', models.FloatField(null=True)),
                ('hostgal2_magerr_i', models.FloatField(null=True)),
                ('hostgal2_magerr_z', models.FloatField(null=True)),
                ('hostgal2_magerr_Y', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaSource',
            fields=[
                ('diaSourceId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ccdVisitId', models.BigIntegerField()),
                ('parentDiaSourceId', models.BigIntegerField(null=True)),
                ('midPointTai', models.FloatField()),
                ('filterName', models.TextField()),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('psFlux', models.FloatField()),
                ('psFluxErr', models.FloatField()),
                ('snr', models.FloatField()),
                ('nobs', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSourceId', models.BigIntegerField(null=True)),
                ('diaObjectId', models.BigIntegerField(null=True)),
                ('detect', models.BooleanField(null=True)),
                ('true_gentype', models.IntegerField(null=True)),
                ('true_genmag', models.FloatField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='diatruth',
            index=models.Index(fields=['diaSourceId'], name='elasticc_di_diaSour_db8f99_idx'),
        ),
        migrations.AddIndex(
            model_name='diatruth',
            index=models.Index(fields=['diaObjectId'], name='elasticc_di_diaObje_f52792_idx'),
        ),
        migrations.AddField(
            model_name='diasource',
            name='diaObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diaobject'),
        ),
        migrations.AddIndex(
            model_name='diaobject',
            index=elasticc.models.LongNameBTreeIndex(elasticc.models.q3c_ang2ipix('ra', 'decl'), name='idx_elasticc_diaobject_q3c'),
        ),
        migrations.AddField(
            model_name='diaforcedsource',
            name='diaObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elasticc.diaobject'),
        ),
        migrations.AddField(
            model_name='diaalertprvsource',
            name='diaAlert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diaalert'),
        ),
        migrations.AddField(
            model_name='diaalertprvsource',
            name='diaSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diasource'),
        ),
        migrations.AddField(
            model_name='diaalertprvforcedsource',
            name='diaAlert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diaalert'),
        ),
        migrations.AddField(
            model_name='diaalertprvforcedsource',
            name='diaForcedSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diaforcedsource'),
        ),
        migrations.AddField(
            model_name='diaalert',
            name='diaObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diaobject'),
        ),
        migrations.AddField(
            model_name='diaalert',
            name='diaSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.diasource'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['dbMessageIndex'], name='elasticc_br_dbMessa_59550d_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['alertId'], name='elasticc_br_alertId_b419c9_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['diaSourceId'], name='elasticc_br_diaSour_ca3044_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokerName', 'classiferName'], name='elasticc_br_brokerN_51024e_idx'),
        ),
        migrations.AddField(
            model_name='brokerclassification',
            name='dbClassifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='elasticc.brokerclassifier'),
        ),
        migrations.AddField(
            model_name='brokerclassification',
            name='dbMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='elasticc.brokermessage'),
        ),
        migrations.AddIndex(
            model_name='diasource',
            index=elasticc.models.LongNameBTreeIndex(elasticc.models.q3c_ang2ipix('ra', 'decl'), name='idx_elasticc_diasource_q3c'),
        ),
    ]
