# Generated by Django 3.2.11 on 2022-03-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0004_alter_brokermessage_topicname'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brokerclassifier',
            name='elasticc_br_brokerN_51024e_idx',
        ),
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='classiferName',
            new_name='classifierName',
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokerName', 'classifierName'], name='elasticc_br_brokerN_38d99f_idx'),
        ),
    ]
