# Generated by Django 3.2.11 on 2022-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0008_auto_20220525_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zpec_err',
            new_name='hostgal_zspec_err',
        ),
    ]
