# Generated by Django 3.2.11 on 2022-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0010_auto_20220606_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaobjecttruth',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diatruth',
            name='id',
        ),
        migrations.AlterField(
            model_name='diaobjecttruth',
            name='diaObjectId',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diatruth',
            name='diaSourceId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
