# Generated by Django 3.2.11 on 2022-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0012_auto_20220617_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatruth',
            name='mjd',
            field=models.FloatField(null=True),
        ),
    ]
