# Generated by Django 3.2.11 on 2022-06-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0014_objecttruth_galsnsep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaobjecttruth',
            old_name='lensedmu',
            new_name='lensdmu',
        ),
    ]
