# Generated by Django 4.0.3 on 2022-07-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0016_alter_diaobjecttruth_diaobjectid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diaalertprvforcedsource',
            unique_together={('diaAlert', 'diaForcedSource')},
        ),
        migrations.AlterUniqueTogether(
            name='diaalertprvsource',
            unique_together={('diaAlert', 'diaSource')},
        ),
    ]
