# Generated by Django 4.0.6 on 2022-08-02 23:47

from django.db import migrations, models

def populate_classificationmap( apps, schema_editor ):
    CMap = apps.get_model( 'elasticc', 'ClassificationMap' )
    cmap = CMap( classId=0, snana_gentype=None, description='Static/Other' )
    cmap.save()
    cmap = CMap( classId=1, snana_gentype=None, description='Non-Recurring' )
    cmap.save()
    cmap = CMap( classId=10, snana_gentype=None, description='Non-Recurring/Other' )
    cmap.save()
    cmap = CMap( classId=11, snana_gentype=None, description='SN-like' )
    cmap.save()
    cmap = CMap( classId=110, snana_gentype=None, description='SN-like/Other' )
    cmap.save()
    cmap = CMap( classId=111, snana_gentype=10, description='Ia' )
    cmap.save()
    cmap = CMap( classId=112, snana_gentype=20, description='Ib/c' )
    cmap.save()
    cmap = CMap( classId=112, snana_gentype=21, description='Ib/c' )
    cmap.save()
    cmap = CMap( classId=112, snana_gentype=25, description='Ib/c' )
    cmap.save()
    cmap = CMap( classId=112, snana_gentype=26, description='Ib/c' )
    cmap.save()
    cmap = CMap( classId=112, snana_gentype=27, description='Ib/c' )
    cmap.save()
    cmap = CMap( classId=113, snana_gentype=30, description='II' )
    cmap.save()
    cmap = CMap( classId=113, snana_gentype=31, description='II' )
    cmap.save()
    cmap = CMap( classId=113, snana_gentype=32, description='II' )
    cmap.save()
    cmap = CMap( classId=113, snana_gentype=35, description='II' )
    cmap.save()
    cmap = CMap( classId=113, snana_gentype=36, description='II' )
    cmap.save()
    cmap = CMap( classId=113, snana_gentype=37, description='II' )
    cmap.save()
    cmap = CMap( classId=114, snana_gentype=12, description='Iax' )
    cmap.save()
    cmap = CMap( classId=115, snana_gentype=11, description='91bg' )
    cmap.save()
    cmap = CMap( classId=12, snana_gentype=None, description='Fast' )
    cmap.save()
    cmap = CMap( classId=120, snana_gentype=None, description='Fast/Other' )
    cmap.save()
    cmap = CMap( classId=121, snana_gentype=50, description='KN' )
    cmap.save()
    cmap = CMap( classId=121, snana_gentype=51, description='KN' )
    cmap.save()
    cmap = CMap( classId=122, snana_gentype=82, description='M-dwarf Flare' )
    cmap.save()
    cmap = CMap( classId=123, snana_gentype=84, description='Dwarf Nova' )
    cmap.save()
    cmap = CMap( classId=124, snana_gentype=87, description='uLens' )
    cmap.save()
    cmap = CMap( classId=124, snana_gentype=88, description='uLens' )
    cmap.save()
    cmap = CMap( classId=124, snana_gentype=89, description='uLens' )
    cmap.save()
    cmap = CMap( classId=13, snana_gentype=None, description='Long' )
    cmap.save()
    cmap = CMap( classId=130, snana_gentype=None, description='Long/Other' )
    cmap.save()
    cmap = CMap( classId=131, snana_gentype=40, description='SLSN' )
    cmap.save()
    cmap = CMap( classId=132, snana_gentype=42, description='TDE' )
    cmap.save()
    cmap = CMap( classId=133, snana_gentype=45, description='ILOT' )
    cmap.save()
    cmap = CMap( classId=134, snana_gentype=46, description='CART' )
    cmap.save()
    cmap = CMap( classId=135, snana_gentype=59, description='PISN' )
    cmap.save()
    cmap = CMap( classId=2, snana_gentype=None, description='Recurring' )
    cmap.save()
    cmap = CMap( classId=20, snana_gentype=None, description='Recurring/Other' )
    cmap.save()
    cmap = CMap( classId=21, snana_gentype=None, description='Periodic' )
    cmap.save()
    cmap = CMap( classId=210, snana_gentype=None, description='Periodic/Other' )
    cmap.save()
    cmap = CMap( classId=211, snana_gentype=90, description='Cepheid' )
    cmap.save()
    cmap = CMap( classId=212, snana_gentype=80, description='RR Lyrae' )
    cmap.save()
    cmap = CMap( classId=213, snana_gentype=91, description='Delta Scuti' )
    cmap.save()
    cmap = CMap( classId=214, snana_gentype=83, description='EB' )
    cmap.save()
    cmap = CMap( classId=215, snana_gentype=None, description='LPV/Mira' )
    cmap.save()
    cmap = CMap( classId=22, snana_gentype=None, description='Non-Periodic' )
    cmap.save()
    cmap = CMap( classId=220, snana_gentype=None, description='Non-Periodic/Other' )
    cmap.save()
    cmap = CMap( classId=221, snana_gentype=60, description='AGN' )
    cmap.save()

class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0018_brokermessage_msghdrtimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classId', models.IntegerField(db_index=True)),
                ('snana_gentype', models.IntegerField(db_index=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RunPython( populate_classificationmap )
    ]
