# Generated by Django 4.0.6 on 2022-08-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0020_alter_diaforcedsource_midpointtai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaobject',
            name='hostgal2_zphot_p50',
            field=models.FloatField(null=True),
        ),
    ]
