# Generated by Django 4.0.6 on 2022-08-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0021_diaobject_hostgal2_zphot_p50'),
    ]

    operations = [
        migrations.RunSQL( "CREATE ROLE postgres_elasticc_ro PASSWORD '20vt5dtuaa0o' LOGIN" ),
        migrations.RunSQL( "GRANT CONNECT ON DATABASE tom_desc TO postgres_elasticc_ro" ),
        migrations.RunSQL( "GRANT USAGE ON SCHEMA public TO postgres_elasticc_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_brokerclassification TO postgres_elasticc_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_brokerclassifier TO postgres_elasticc_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_brokermessage TO postgres_elasticc_ro" ),
        migrations.RunSQL( "CREATE ROLE postgres_elasticc_admin_ro PASSWORD 'nfnihnak8u8j' LOGIN" ),
        migrations.RunSQL( "GRANT CONNECT ON DATABASE tom_desc TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT USAGE ON SCHEMA public TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_brokerclassification TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_brokerclassifier TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_brokermessage TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_classificationmap TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diaalert TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diaalertprvforcedsource TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diaalertprvsource TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diaforcedsource TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diaobject TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diaobjecttruth TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diasource TO postgres_elasticc_admin_ro" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_diatruth TO postgres_elasticc_admin_ro" )
    ]
