# Generated by Django 4.0.6 on 2022-08-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0024_alter_brokerclassification_dbmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokerclassifier',
            old_name='classiferId',
            new_name='classifierId',
        ),
    ]
