# Generated by Django 4.0.6 on 2022-08-08 16:30

from django.db import migrations

def populate_classidofgentype( apps, shcema_editor ):
    CMap = apps.get_model( 'elasticc', 'ClassIdOfGentype' )

    for gentype in [ 10, 20, 21, 25, 26, 27, 30, 31, 32, 35, 36, 37, 12, 11,
                     50, 51, 82, 84, 87, 88, 89, 40, 42, 45, 46, 59 ]:
        cmap = CMap( classId=1, gentype=gentype, description='Non-Recurring',
                     exactmatch=False, categorymatch=False )
        cmap.save()

    for gentype in [ 10, 20, 21, 25, 26, 27, 30, 31, 32, 35, 36, 37, 12, 11 ]:
        cmap = CMap( classId=11, gentype=gentype, description='SN-like',
                     exactmatch=False, categorymatch=True )
        cmap.save()
        
    cmap = CMap( classId=111, gentype=10, description='Ia', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=112, gentype=20, description='Ib/c', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=112, gentype=21, description='Ib/c', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=112, gentype=25, description='Ib/c', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=112, gentype=26, description='Ib/c', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=112, gentype=27, description='Ib/c', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=113, gentype=30, description='II', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=113, gentype=31, description='II', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=113, gentype=32, description='II', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=113, gentype=35, description='II', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=113, gentype=36, description='II', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=113, gentype=37, description='II', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=114, gentype=12, description='Iax', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=115, gentype=11, description='91bg', exactmatch=True, categorymatch=True )
    cmap.save()

    for gentype in [ 50, 51, 82, 84, 87, 88, 89 ]:
        cmap = CMap( classId=12, gentype=gentype, description='Fast',
                     exactmatch=False, categorymatch=True )
        cmap.save()
        
    cmap = CMap( classId=121, gentype=50, description='KN', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=121, gentype=51, description='KN', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=122, gentype=82, description='M-dwarf Flare', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=123, gentype=84, description='Dwarf Nova', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=124, gentype=87, description='uLens', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=124, gentype=88, description='uLens', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=124, gentype=89, description='uLens', exactmatch=True, categorymatch=True )
    cmap.save()

    for gentype in [ 40, 42, 45, 46, 59 ]:
        cmap = CMap( classId=13, gentype=gentype, description='Long',
                     exactmatch=False, categorymatch=True )
        cmap.save()
    cmap = CMap( classId=131, gentype=40, description='SLSN', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=132, gentype=42, description='TDE', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=133, gentype=45, description='ILOT', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=134, gentype=46, description='CART', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=135, gentype=59, description='PISN', exactmatch=True, categorymatch=True )
    cmap.save()

    for gentype in [ 90, 80, 91, 83, 60 ]:
        cmap = CMap( classId=2, gentype=gentype, description='Recurring',
                     exactmatch=False, categorymatch=False )
        cmap.save()

    for gentype in [ 90, 80, 91, 83 ]:
        cmap = CMap( classId=20, gentype=gentype, description='Periodic',
                     exactmatch=False, categorymatch=True )
        cmap.save()

    cmap = CMap( classId=211, gentype=90, description='Cepheid', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=212, gentype=80, description='RR Lyrae', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=213, gentype=91, description='Delta Scuti', exactmatch=True, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=214, gentype=83, description='EB', exactmatch=True, categorymatch=True )
    cmap.save()

    cmap = CMap( classId=22, gentype=60, description='Non-Periodic', exactmatch=False, categorymatch=True )
    cmap.save()
    cmap = CMap( classId=221, gentype=60, description='AGN', exactmatch=True, categorymatch=True )
    cmap.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0028_classidofgentype_and_more'),
    ]

    operations = [
        migrations.RunPython( populate_classidofgentype )
    ]
