# Generated by Django 4.0.6 on 2022-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0033_alter_diaalert_alertsenttimestamp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokerName', 'brokerVersion', 'classifierName', 'classifierParams'], name='elasticc_br_brokerN_42e68f_idx'),
        ),
    ]
