# Generated by Django 3.2.11 on 2022-03-25 21:42

from django.db import migrations, models
import django.db.models.deletion
import stream.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcBrokerClassification',
            fields=[
                ('dbClassificationIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('classId', models.IntegerField()),
                ('probability', models.FloatField()),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerClassifier',
            fields=[
                ('dbClassifierIndex', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('brokerName', models.CharField(max_length=100)),
                ('brokerVersion', models.TextField(null=True)),
                ('classiferName', models.CharField(max_length=200)),
                ('classifierParams', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerMessage',
            fields=[
                ('dbMessageIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('streamMessageId', models.BigIntegerField(null=True)),
                ('topicName', models.CharField(max_length=200)),
                ('alertId', models.BigIntegerField()),
                ('diaSourceId', models.BigIntegerField()),
                ('descIngestTimestamp', models.DateTimeField(auto_now_add=True)),
                ('elasticcPublishTimestamp', models.DateTimeField(null=True)),
                ('brokerIngestTimestamp', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaAlert',
            fields=[
                ('alertId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaAlertPrvForcedSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaAlertPrvSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaForcedSource',
            fields=[
                ('diaForcedSourceId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ccdVisitId', models.BigIntegerField()),
                ('midPointTai', models.FloatField()),
                ('filterName', models.TextField()),
                ('psFlux', models.FloatField()),
                ('psFluxErr', models.FloatField()),
                ('totFlux', models.FloatField()),
                ('totFluxErr', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElasticcDiaObject',
            fields=[
                ('diaObjectId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('mwebv', models.FloatField(null=True)),
                ('mwebv_err', models.FloatField(null=True)),
                ('z_final', models.FloatField(null=True)),
                ('z_final_err', models.FloatField(null=True)),
                ('hostgal_ellipticity', models.FloatField(null=True)),
                ('hostgal_sqradius', models.FloatField(null=True)),
                ('hostgal_z', models.FloatField(null=True)),
                ('hostgal_z_err', models.FloatField(null=True)),
                ('hostgal_zphot_q10', models.FloatField(null=True)),
                ('hostgal_zphot_q20', models.FloatField(null=True)),
                ('hostgal_zphot_q30', models.FloatField(null=True)),
                ('hostgal_zphot_q40', models.FloatField(null=True)),
                ('hostgal_zphot_q50', models.FloatField(null=True)),
                ('hostgal_zphot_q60', models.FloatField(null=True)),
                ('hostgal_zphot_q70', models.FloatField(null=True)),
                ('hostgal_zphot_q80', models.FloatField(null=True)),
                ('hostgal_zphot_q90', models.FloatField(null=True)),
                ('hostgal_zphot_q99', models.FloatField(null=True)),
                ('hostgal_mag_u', models.FloatField(null=True)),
                ('hostgal_mag_g', models.FloatField(null=True)),
                ('hostgal_mag_r', models.FloatField(null=True)),
                ('hostgal_mag_i', models.FloatField(null=True)),
                ('hostgal_mag_z', models.FloatField(null=True)),
                ('hostgal_mag_Y', models.FloatField(null=True)),
                ('hostgal_ra', models.FloatField(null=True)),
                ('hostgal_dec', models.FloatField(null=True)),
                ('hostgal_snsep', models.FloatField(null=True)),
                ('hostgal_magerr_u', models.FloatField(null=True)),
                ('hostgal_magerr_g', models.FloatField(null=True)),
                ('hostgal_magerr_r', models.FloatField(null=True)),
                ('hostgal_magerr_i', models.FloatField(null=True)),
                ('hostgal_magerr_z', models.FloatField(null=True)),
                ('hostgal_magerr_Y', models.FloatField(null=True)),
                ('hostgal2_ellipticity', models.FloatField(null=True)),
                ('hostgal2_sqradius', models.FloatField(null=True)),
                ('hostgal2_z', models.FloatField(null=True)),
                ('hostgal2_z_err', models.FloatField(null=True)),
                ('hostgal2_zphot_q10', models.FloatField(null=True)),
                ('hostgal2_zphot_q20', models.FloatField(null=True)),
                ('hostgal2_zphot_q30', models.FloatField(null=True)),
                ('hostgal2_zphot_q40', models.FloatField(null=True)),
                ('hostgal2_zphot_q50', models.FloatField(null=True)),
                ('hostgal2_zphot_q60', models.FloatField(null=True)),
                ('hostgal2_zphot_q70', models.FloatField(null=True)),
                ('hostgal2_zphot_q80', models.FloatField(null=True)),
                ('hostgal2_zphot_q90', models.FloatField(null=True)),
                ('hostgal2_zphot_q99', models.FloatField(null=True)),
                ('hostgal2_mag_u', models.FloatField(null=True)),
                ('hostgal2_mag_g', models.FloatField(null=True)),
                ('hostgal2_mag_r', models.FloatField(null=True)),
                ('hostgal2_mag_i', models.FloatField(null=True)),
                ('hostgal2_mag_z', models.FloatField(null=True)),
                ('hostgal2_mag_Y', models.FloatField(null=True)),
                ('hostgal2_ra', models.FloatField(null=True)),
                ('hostgal2_dec', models.FloatField(null=True)),
                ('hostgal2_snsep', models.FloatField(null=True)),
                ('hostgal2_magerr_u', models.FloatField(null=True)),
                ('hostgal2_magerr_g', models.FloatField(null=True)),
                ('hostgal2_magerr_r', models.FloatField(null=True)),
                ('hostgal2_magerr_i', models.FloatField(null=True)),
                ('hostgal2_magerr_z', models.FloatField(null=True)),
                ('hostgal2_magerr_Y', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaSource',
            fields=[
                ('diaSourceId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ccdVisitId', models.BigIntegerField()),
                ('parentDiaSourceId', models.BigIntegerField(null=True)),
                ('midPointTai', models.FloatField()),
                ('filterName', models.TextField()),
                ('ra', models.FloatField()),
                ('decl', models.FloatField()),
                ('psFlux', models.FloatField()),
                ('psFluxErr', models.FloatField()),
                ('snr', models.FloatField()),
                ('nobs', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSourceId', models.BigIntegerField(null=True)),
                ('diaObjectId', models.BigIntegerField(null=True)),
                ('detect', models.BooleanField(null=True)),
                ('true_gentype', models.IntegerField(null=True)),
                ('true_genmag', models.FloatField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaSourceId'], name='stream_elas_diaSour_e926b6_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaObjectId'], name='stream_elas_diaObje_e18552_idx'),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='diaObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaobject'),
        ),
        migrations.AddIndex(
            model_name='elasticcdiaobject',
            index=stream.models.LongNameBTreeIndex(stream.models.q3c_ang2ipix('ra', 'decl'), name='idx_stream_elasticcdiaobject_q3c'),
        ),
        migrations.AddField(
            model_name='elasticcdiaforcedsource',
            name='diaObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaobject'),
        ),
        migrations.AddField(
            model_name='elasticcdiaalertprvsource',
            name='diaAlert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaalert'),
        ),
        migrations.AddField(
            model_name='elasticcdiaalertprvsource',
            name='diaSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiasource'),
        ),
        migrations.AddField(
            model_name='elasticcdiaalertprvforcedsource',
            name='diaAlert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaalert'),
        ),
        migrations.AddField(
            model_name='elasticcdiaalertprvforcedsource',
            name='diaForcedSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaforcedsource'),
        ),
        migrations.AddField(
            model_name='elasticcdiaalert',
            name='diaObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaobject'),
        ),
        migrations.AddField(
            model_name='elasticcdiaalert',
            name='diaSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiasource'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokermessage',
            index=models.Index(fields=['dbMessageIndex'], name='stream_elas_dbMessa_8a0f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokermessage',
            index=models.Index(fields=['alertId'], name='stream_elas_alertId_59787d_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokermessage',
            index=models.Index(fields=['diaSourceId'], name='stream_elas_diaSour_b85766_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassifier',
            index=models.Index(fields=['brokerName', 'classiferName'], name='stream_elas_brokerN_d764af_idx'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='dbClassifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokerclassifier'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='dbMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokermessage'),
        ),
        migrations.AddIndex(
            model_name='elasticcdiasource',
            index=stream.models.LongNameBTreeIndex(stream.models.q3c_ang2ipix('ra', 'decl'), name='idx_stream_elasticcdiasource_q3c'),
        ),
    ]
