# Generated by Django 3.2.11 on 2022-02-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('ra', models.FloatField(null=True)),
                ('decl', models.FloatField(null=True)),
                ('parsed_message', models.JSONField(default=dict)),
                ('raw_message', models.JSONField(default=dict)),
                ('parsed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerClassification',
            fields=[
                ('dbClassificationIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('alertId', models.BigIntegerField()),
                ('classId', models.IntegerField()),
                ('probability', models.FloatField()),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerClassifier',
            fields=[
                ('dbClassifierIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('brokerName', models.CharField(max_length=100)),
                ('brokerVersion', models.TextField(null=True)),
                ('classiferName', models.CharField(max_length=200)),
                ('classifierVersion', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerMessage',
            fields=[
                ('dbMessageIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('streamMessageId', models.BigIntegerField(null=True)),
                ('topicName', models.CharField(max_length=200)),
                ('descIngestTimestamp', models.DateTimeField(auto_now_add=True)),
                ('elasticcPublishTimestamp', models.DateTimeField(null=True)),
                ('brokerIngestTimestamp', models.DateTimeField(null=True)),
                ('brokerPublishTimestamp', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaObject',
            fields=[
                ('diaObjectId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('ra', models.FloatField(null=True)),
                ('decl', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaSource',
            fields=[
                ('diaSourceId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('midPointTai', models.FloatField()),
                ('filterName', models.TextField()),
                ('ra', models.FloatField(null=True)),
                ('decl', models.FloatField(null=True)),
                ('apFlux', models.FloatField()),
                ('apFluxErr', models.FloatField()),
                ('nobs', models.FloatField(null=True)),
                ('mwebv', models.FloatField(null=True)),
                ('mwebv_err', models.FloatField(null=True)),
                ('z_final', models.FloatField(null=True)),
                ('z_final_err', models.FloatField(null=True)),
                ('hostgal_z', models.FloatField(null=True)),
                ('hostgal_z_err', models.FloatField(null=True)),
                ('hostgal_snsep', models.FloatField(null=True)),
                ('hostgal_mag_u', models.FloatField(null=True)),
                ('hostgal_mag_g', models.FloatField(null=True)),
                ('hostgal_mag_r', models.FloatField(null=True)),
                ('hostgal_mag_i', models.FloatField(null=True)),
                ('hostgal_mag_z', models.FloatField(null=True)),
                ('hostgal_mag_Y', models.FloatField(null=True)),
                ('hostgal_magerr_u', models.FloatField(null=True)),
                ('hostgal_magerr_g', models.FloatField(null=True)),
                ('hostgal_magerr_r', models.FloatField(null=True)),
                ('hostgal_magerr_i', models.FloatField(null=True)),
                ('hostgal_magerr_z', models.FloatField(null=True)),
                ('hostgal_magerr_Y', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcDiaTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSourceId', models.BigIntegerField(null=True)),
                ('diaObjectId', models.BigIntegerField(null=True)),
                ('detect', models.BooleanField(null=True)),
                ('true_gentype', models.IntegerField(null=True)),
                ('true_genmag', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RknopTest',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('ra', models.FloatField(null=True)),
                ('decl', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('right_ascension', models.FloatField(blank=True, null=True)),
                ('declination', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField(default=dict)),
                ('tag', models.CharField(max_length=200)),
                ('sequence_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaSourceId'], name='stream_elas_diaSour_e926b6_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaObjectId'], name='stream_elas_diaObje_e18552_idx'),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='diaObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiaobject'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokermessage',
            index=models.Index(fields=['dbMessageIndex', 'topicName'], name='stream_elas_dbMessa_63762e_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassifier',
            index=models.Index(fields=['dbClassifierIndex', 'brokerName', 'classiferName'], name='stream_elas_dbClass_a63361_idx'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='dbClassifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokerclassifier'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='dbMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokermessage'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='diaSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcdiasource'),
        ),
        migrations.AddField(
            model_name='alert',
            name='events',
            field=models.ManyToManyField(to='stream.Event'),
        ),
        migrations.AddField(
            model_name='alert',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.topic'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassification',
            index=models.Index(fields=['dbClassificationIndex'], name='stream_elas_dbClass_5cc935_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['timestamp'], name='timestamp_idx'),
        ),
    ]
