# Generated by Django 3.2.6 on 2021-11-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcBrokerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertId', models.CharField(max_length=200)),
                ('classifierNames', models.CharField(max_length=255)),
                ('class_10', models.FloatField(null=True)),
                ('class_20', models.FloatField(null=True)),
                ('class_020', models.FloatField(null=True)),
                ('class_120', models.FloatField(null=True)),
                ('class_0120', models.FloatField(null=True)),
                ('class_1120', models.FloatField(null=True)),
                ('class_01120', models.FloatField(null=True)),
                ('class_11120', models.FloatField(null=True)),
                ('class_011120', models.FloatField(null=True)),
                ('class_111120', models.FloatField(null=True)),
                ('elasticc_publish_timestamp', models.DateTimeField()),
                ('broker_ingest_timestamp', models.DateTimeField(null=True)),
                ('broker_publish_timestamp', models.DateTimeField(null=True)),
                ('desc_ingest_timestamp', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='elasticcbrokeralert',
            index=models.Index(fields=['alertId'], name='alertId'),
        ),
    ]
