# Generated by Django 3.2.8 on 2021-11-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20211108_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticcbrokeralert',
            name='message_bytes',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='elasticcbrokeralert',
            name='elasticc_publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
