# Generated by Django 3.2.9 on 2021-11-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20211113_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcBrokerClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertId', models.CharField(max_length=200)),
                ('diaObjectId', models.CharField(max_length=200)),
                ('classifierName', models.CharField(max_length=200, null=True)),
                ('classId', models.CharField(max_length=50, null=True)),
                ('probability', models.FloatField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerMetadata',
            fields=[
                ('brokerMessageId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descIngestTimestamp', models.DateTimeField(auto_now_add=True)),
                ('elasticcPublishTimestamp', models.DateTimeField(null=True)),
                ('brokerIngestTimestamp', models.DateTimeField(null=True)),
                ('brokerPublishTimestamp', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ElasticcBrokerAlert',
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='brokerMessageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokermetadata'),
        ),
    ]
