# Generated by Django 3.2.11 on 2022-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20220203_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='hostgal_ellipticity',
            field=models.FloatField(null=True),
        ),
    ]
