# Generated by Django 3.2.11 on 2022-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_elasticcdiaobject_hostgal_ellipticity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elasticcdiaobject',
            name='hostgal2_zphot_pz50',
        ),
        migrations.RemoveField(
            model_name='elasticcdiaobject',
            name='hostgal_zphot_pz50',
        ),
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='hostgal2_zphot_q99',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='hostgal_zphot_q99',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='mwebv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='mwebv_err',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='z_final',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiaobject',
            name='z_final_err',
            field=models.FloatField(null=True),
        ),
    ]
