# Generated by Django 3.2.9 on 2021-11-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20211124_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticcbrokerclassification',
            name='brokerMessageId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokermetadata'),
        ),
    ]
