# Generated by Django 3.2.10 on 2021-12-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_alter_elasticcbrokerclassification_brokermessageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcBrokerClassification2',
            fields=[
                ('dbClassificationIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('alertId', models.BigIntegerField()),
                ('diaObjectId', models.BigIntegerField()),
                ('classId', models.IntegerField()),
                ('probability', models.FloatField()),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerClassifier',
            fields=[
                ('dbClassifierIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('brokerName', models.CharField(max_length=100)),
                ('classiferName', models.CharField(max_length=200)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticcBrokerMessage',
            fields=[
                ('dbMessageIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('streamMessageId', models.BigIntegerField(null=True)),
                ('topicName', models.CharField(max_length=200)),
                ('descIngestTimestamp', models.DateTimeField(auto_now_add=True)),
                ('elasticcPublishTimestamp', models.DateTimeField(null=True)),
                ('brokerIngestTimestamp', models.DateTimeField(null=True)),
                ('brokerPublishTimestamp', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ElasticcBrokerClassification',
        ),
        migrations.DeleteModel(
            name='ElasticcBrokerMetadata',
        ),
        migrations.AddIndex(
            model_name='elasticcbrokermessage',
            index=models.Index(fields=['dbMessageIndex'], name='stream_elas_dbMessa_8a0f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassifier',
            index=models.Index(fields=['dbClassifierIndex', 'brokerName', 'classiferName'], name='stream_elas_dbClass_a63361_idx'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification2',
            name='dbClassifierIndex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokerclassifier'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification2',
            name='dbMessageIndex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokermessage'),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassification2',
            index=models.Index(fields=['dbClassificationIndex', 'dbClassifierIndex', 'dbMessageIndex'], name='stream_elas_dbClass_2bca52_idx'),
        ),
    ]
