# Generated by Django 3.2.10 on 2021-12-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20211208_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcBrokerClassification',
            fields=[
                ('dbClassificationIndex', models.BigAutoField(primary_key=True, serialize=False)),
                ('alertId', models.BigIntegerField()),
                ('diaObjectId', models.BigIntegerField()),
                ('classId', models.IntegerField()),
                ('probability', models.FloatField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dbClassifierIndex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokerclassifier')),
                ('dbMessageIndex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcbrokermessage')),
            ],
        ),
        migrations.DeleteModel(
            name='ElasticcBrokerClassification2',
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassification',
            index=models.Index(fields=['dbClassificationIndex', 'dbClassifierIndex', 'dbMessageIndex'], name='stream_elas_dbClass_61c7c7_idx'),
        ),
    ]
