# Generated by Django 3.2.10 on 2021-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_auto_20211208_0741'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='elasticcbrokermessage',
            name='stream_elas_dbMessa_8a0f8c_idx',
        ),
        migrations.AddIndex(
            model_name='elasticcbrokermessage',
            index=models.Index(fields=['dbMessageIndex', 'topicName'], name='stream_elas_dbMessa_63762e_idx'),
        ),
    ]
