# Generated by Django 3.2.11 on 2022-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_auto_20211208_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='RknopTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
