# Generated by Django 3.2.11 on 2022-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_elasticcalert_elasticcdiaobject_elasticcdiasource_elasticcssobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rknoptest',
            name='id',
        ),
        migrations.AlterField(
            model_name='rknoptest',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
