# Generated by Django 3.2.11 on 2022-01-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_auto_20220111_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elasticcssobject',
            old_name='discoveriySubmissionDate',
            new_name='discoverySubmissionDate',
        ),
    ]
