# Generated by Django 3.2.11 on 2022-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0016_auto_20220114_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_mag_Y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_mag_g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_mag_i',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_mag_r',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_mag_u',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_mag_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_magerr_Y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_magerr_g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_magerr_i',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_magerr_r',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_magerr_u',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_magerr_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiasource',
            name='hostgal_z_err',
            field=models.FloatField(null=True),
        ),
    ]
