# Generated by Django 3.2.11 on 2022-01-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0017_auto_20220128_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcDiaTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect', models.BooleanField()),
                ('true_gentype', models.IntegerField()),
                ('true_genmag', models.FloatField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='elasticcbrokerclassification',
            name='stream_elas_dbClass_61c7c7_idx',
        ),
        migrations.RenameField(
            model_name='elasticcbrokerclassification',
            old_name='dbClassifierIndex',
            new_name='dbClassifier',
        ),
        migrations.RenameField(
            model_name='elasticcbrokerclassification',
            old_name='dbMessageIndex',
            new_name='dbMessage',
        ),
        migrations.RemoveField(
            model_name='elasticcbrokerclassification',
            name='diaObjectId',
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassification',
            name='diaSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stream.elasticcdiasource'),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassifier',
            name='brokerVersion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcbrokerclassifier',
            name='classifierVersion',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='elasticcbrokerclassification',
            index=models.Index(fields=['dbClassificationIndex'], name='stream_elas_dbClass_5cc935_idx'),
        ),
        migrations.AddField(
            model_name='elasticcdiatruth',
            name='diaSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.elasticcdiasource', unique=True),
        ),
    ]
