# Generated by Django 3.2.11 on 2022-01-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0018_auto_20220131_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elasticcdiatruth',
            name='diaSource',
        ),
        migrations.AddField(
            model_name='elasticcdiatruth',
            name='diaObjectId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='elasticcdiatruth',
            name='diaSourceId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='elasticcdiatruth',
            name='detect',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='elasticcdiatruth',
            name='true_genmag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='elasticcdiatruth',
            name='true_gentype',
            field=models.IntegerField(null=True),
        ),
    ]
