# Generated by Django 3.2.11 on 2022-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0019_auto_20220131_1908'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaSourceId', 'diaObjectId'], name='stream_elas_diaSour_66d316_idx'),
        ),
    ]
