# Generated by Django 3.2.11 on 2022-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0020_elasticcdiatruth_stream_elas_diasour_66d316_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='elasticcdiatruth',
            name='stream_elas_diaSour_66d316_idx',
        ),
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaSourceId'], name='stream_elas_diaSour_e926b6_idx'),
        ),
        migrations.AddIndex(
            model_name='elasticcdiatruth',
            index=models.Index(fields=['diaObjectId'], name='stream_elas_diaObje_e18552_idx'),
        ),
    ]
