# Generated by Django 4.2.7 on 2024-04-23 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryQueue',
            fields=[
                ('queryid', models.UUIDField(primary_key=True, serialize=False)),
                ('submitted', models.DateTimeField()),
                ('started', models.DateTimeField(default=None, null=True)),
                ('finished', models.DateTimeField(default=None, null=True)),
                ('error', models.BooleanField(default=False)),
                ('errortext', models.TextField(default=None, null=True)),
                ('queries', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('subdicts', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('format', models.TextField(default='csv')),
            ],
        ),
    ]
