apiVersion: batch/v1
kind: CronJob
metadata:
  name: tom-send-alerts
  namespace: desc-tom-rknop-dev
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            field.cattle.io/ports: '[[]]'
            nersc.gov/collab_uids: "99895"
            nersc.gov/gid: "95089"
            nersc.gov/gids: 60152,57177,95089,96414,99895
            nersc.gov/roles: user
            nersc.gov/uid: "95089"
            nersc.gov/username: raknop
          creationTimestamp: null
        spec:
          containers:
          - command: ['python']
            args: ['manage.py', 'send_elasticc2_alerts',
               '-a', '36',
               '-k', 'public.alerts.ztf.uw.edu:9092',
               '--wfd-topic', 'elasticc2-2-wfd',
               '--ddf-full-topic', 'elasticc2-2-ddf-full',
               '--ddf-limited-topic', 'elasticc2-2-ddf-limited',
               '--do']
            # args: ['manage.py', 'send_elasticc2_alerts',
            #    '-a', '3',
            #    '-k', 'kafka-server:9092',
            #    '--wfd-topic', 'alerts-wfd',
            #    '--ddf-full-topic', 'alerts-ddf-full',
            #    '--ddf-limited-topic', 'alerts-ddf-limited',
            #    '--do']
            env:
            - name: DB_HOST
              value: tom-postgres
            - name: DB_NAME
              value: tom_desc
            - name: DB_PASS
              value: fragile
            - name: DB_USER
              value: postgres
            - name: MONGODB_ADMIN
              valueFrom:
                secretKeyRef:
                  name: tom-secrets
                  key: mongodb_admin
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tom-secrets
                  key: mongodb_admin_passwd
            - name: MONGODB_ALERT_WRITER
              valueFrom:
                secretKeyRef:
                  name: tom-secrets
                  key: mongodb_alert_writer
            - name: MONGODB_ALERT_WRITER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tom-secrets
                  key: mongodb_alert_writer_password
            - name: MONGODB_ALERT_READER
              valueFrom:
                secretKeyRef:
                  name: tom-secrets
                  key: mongodb_alert_reader
            - name: MONGODB_ALERT_READER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tom-secrets
                  key: mongodb_alert_reader_password
            image: registry.nersc.gov/m1727/raknop/tom_server_bindmount
            imagePullPolicy: Always
            name: tom-send-alerts
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 95089
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /secrets
              name: tom-secrets
            - mountPath: /tom_desc
              name: tom-deployment
            - mountPath: /logs
              name: tom-logs
            workingDir: /tom_desc
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 57177
          terminationGracePeriodSeconds: 30
          imagePullSecrets:
            - name: registry-nersc
          volumes:
          - name: tom-secrets
            secret:
              defaultMode: 256
              optional: false
              secretName: tom-secrets
          - hostPath:
              path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/tom_desc/tom_desc
              type: Directory
            name: tom-deployment
          - hostPath:
              path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/logs
              type: Directory
            name: tom-logs
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: true
