apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tom-rknop-dev-postgres-pvc-20250213
  namespace: desc-tom-rknop-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
