apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-brokerpoll
  namespace: desc-tom-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-tom-brokerpoll
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 60152,57177,95089,96414,99895
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-tom-brokerpoll
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: tom-postgres
        - name: DB_NAME
          value: tom_desc
        - name: DB_PASS
          value: fragile
        - name: DB_USER
          value: postgres
        - name: MONGODB_ADMIN
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin_passwd
        - name: MONGODB_ALERT_WRITER
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_writer
        - name: MONGODB_ALERT_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_writer_password
        - name: MONGODB_ALERT_READER
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_reader
        - name: MONGODB_ALERT_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_reader_password
        - name: ALERCE_TOPIC_RELDATEOFFSET
          value: '-36'
        - name: ALERCE_KAFKA_SERVER
          value: b-3-public.publicproduction.o8ncxm.c18.kafka.us-east-1.amazonaws.com:9196,b-2-public.publicproduction.o8ncxm.c18.kafka.us-east-1.amazonaws.com:9196,b-1-public.publicproduction.o8ncxm.c18.kafka.us-east-1.amazonaws.com:9196
        - name: FINK_GROUP_ID
          value: lsstfr-johann
        - name: FINK_SERVER
          value: 134.158.74.95:24499,
        - name: FINK_TOPIC
          value: fink_early_sn_candidates_ztf
        - name: FINK_USERNAME
          value: johann
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/pitt_google_auth_key.json
        - name: GOOGLE_CLOUD_PROJECT
          value: elasticc-challenge
        image: registry.nersc.gov/m1727/raknop/tom_server_bindmount:rknop-dev
        imagePullPolicy: Always
        name: tom-brokerpoll
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: tom-secrets
        - mountPath: /tom_desc
          name: tom-deployment
        - mountPath: /logs
          name: tom-logs
        command: [ "dumb-init" ]
        args:
          - -r
          - 15:10
          - python
          - manage.py
          - brokerpoll2
          - --do-antares
          - --antares-topic
          - elasticc2-2
          - --do-pitt
          - --pitt-project
          - elasticc-challenge
          - --pitt-topic
          - elasticc-SuperNNova
          - --do-alerce
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 57177
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: tom-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: tom-secrets
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/tom_desc/tom_desc
          type: Directory
        name: tom-deployment
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/logs
          type: Directory
        name: tom-logs
