---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-query-runner
  namespace: desc-tom-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-tom-query-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 60152,57177,95089,96414,99895
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-tom-query-runner
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: tom-postgres
        - name: DB_NAME
          value: tom_desc
        - name: DB_PASS
          value: fragile
        - name: DB_USER
          value: postgres
        - name: MONGODB_ADMIN
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin_passwd
        - name: MONGODB_ALERT_WRITER
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_writer
        - name: MONGODB_ALERT_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_writer_password
        - name: MONGODB_ALERT_READER
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_reader
        - name: MONGODB_ALERT_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_reader_password
        image: registry.nersc.gov/m1727/raknop/tom_server_bindmount:rknop-dev
        imagePullPolicy: Always
        name: tom-query-runner
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: tom-secrets
        - mountPath: /tom_desc
          name: tom-deployment
        - mountPath: /query_results
          name: tom-query-results
        - mountPath: /logs
          name: tom-logs
        command: [ 'python' ]
        args: [ 'manage.py', 'long_query_runner', '-l' ]
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 57177
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: tom-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: tom-secrets
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/tom_desc/tom_desc
          type: Directory
        name: tom-deployment
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/query_results
          type: Directory
        name: tom-query-results
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/rknop_dev/logs
          type: Directory
        name: tom-logs
---
apiVersion: v1
kind: Service
metadata:
  name: tom-query-runner
  namespace: desc-tom-rknop-dev
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-tom-query-runner
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
