apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tom-rknop-dev-postgres-pvc
  namespace: desc-tom
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
