---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: desc-tom-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "70268"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 95089,57177,60152
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-mongodb
    spec:
      initContainers:
      - args:
        - -c
        - chown 999:999 /data
        command:
        - /bin/sh
        image: busybox
        imagePullPolicy: Always
        name: mongodb-volume-mount-hack
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: mongodb-datadir
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongodb_admin
              name: tom-secrets
              optional: false
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb_admin_passwd
              name: tom-secrets
              optional: false
        - name: MONGO_ALERT_WRITER_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_writer
              name: tom-secrets
              optional: false
        - name: MONGO_ALERT_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_writer_password
              name: tom-secrets
              optional: false
        - name: MONGO_ALERT_READER_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_reader
              name: tom-secrets
              optional: false
        - name: MONGO_ALERT_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_reader_password
              name: tom-secrets
              optional: false
        image: registry.nersc.gov/m1727/rknop/tom-mongodb:latest
        imagePullPolicy: Always
        name: mongodb
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
#        ports:
#        - name: mongodb
#          containerPort: 27017
#          protocol: TCP
        volumeMounts:
        - mountPath: /mongodb-data
          name: mongodb-datadir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: mongodb-datadir
        persistentVolumeClaim:
          claimName: rknop-dev-mongodb-pvc-20241030
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: desc-tom-rknop-dev
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-desc-tom-rknop-dev-mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
