apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tom-2-postgres-pvc
  namespace: desc-tom-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
