apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tom-2-alerts-sent-hists
  namespace: desc-tom-2
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            field.cattle.io/ports: '[[]]'
            nersc.gov/collab_uids: "70268"
            nersc.gov/gid: "95089"
            nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,92576,95089,96414
            nersc.gov/roles: user
            nersc.gov/uid: "95089"
            nersc.gov/username: raknop
          creationTimestamp: null
        spec:
          containers:
          - command: ['python']
            args: ['manage.py', 'update_alerts_sent_2' ]
            env:
            - name: DB_HOST
              value: tom-2-postgres
            - name: DB_NAME
              value: tom_desc
            - name: DB_PASS
              value: fragile
            - name: DB_USER
              value: postgres
            image: registry.nersc.gov/m1727/raknop/tom_desc_bindmount:chimaera
            imagePullPolicy: Always
            name: tom-2-send-alerts
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 95089
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /secrets
              name: tom-2-secrets
            - mountPath: /tom_desc
              name: tom-2-deployment
            workingDir: /tom_desc
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 57177
          terminationGracePeriodSeconds: 30
          volumes:
          - name: tom-2-secrets
            secret:
              defaultMode: 256
              optional: false
              secretName: tom-2-secrets
          - hostPath:
              path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/production-2/tom_desc/tom_desc
              type: Directory
            name: tom-2-deployment
  schedule: 0 6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
