apiVersion: batch/v1
kind: CronJob
metadata:
  name: tom-2-query-pruner
  namespace: desc-tom-2
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            field.cattle.io/ports: '[[]]'
            nersc.gov/collab_uids: "70268"
            nersc.gov/gid: "95089"
            nersc.gov/gids: 95089,60152,57177,96414
            nersc.gov/roles: user
            nersc.gov/uid: "95089"
            nersc.gov/username: raknop
          creationTimestamp: null
        spec:
          containers:
          - command: ['python']
            args: ['manage.py', 'long_query_runner', '-p', '1']
            env:
            - name: DB_HOST
              value: tom-2-postgres
            - name: DB_NAME
              value: tom_desc
            - name: DB_PASS
              value: fragile
            - name: DB_USER
              value: postgres
            image: registry.nersc.gov/m1727/raknop/tom_server_bindmount_dev
            imagePullPolicy: Always
            name: tom-2-query-pruner
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 95089
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /secrets
              name: tom-2-secrets
            - mountPath: /tom_desc
              name: tom-2-deployment
            - mountPath: /query_results
              name: tom-2-query-results
            workingDir: /tom_desc
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 57177
          terminationGracePeriodSeconds: 30
          imagePullSecrets:
            - name: registry-nersc
          volumes:
          - name: tom-2-secrets
            secret:
              defaultMode: 256
              optional: false
              secretName: tom-2-secrets
          - hostPath:
              path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/production-2/tom_desc/tom_desc
              type: Directory
            name: tom-2-deployment
          - hostPath:
              path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/production-2/query_results
              type: Directory
            name: tom-2-query-results
  schedule: 25 8 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
