apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: desc-tom-2-zookeeper-data-pvc
  namespace: desc-tom-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
