# Generated by Django 3.2.11 on 2022-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticcPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('elasticc_admin', 'elasticc admin'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
