# Generated by Django 3.2.11 on 2022-03-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0003_alter_elasticcpermissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokermessage',
            name='topicName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
