# Generated by Django 3.2.11 on 2022-03-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0005_auto_20220329_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerclassification',
            name='dbClassifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.brokerclassifier'),
        ),
        migrations.AlterField(
            model_name='brokerclassification',
            name='dbMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticc.brokermessage'),
        ),
    ]
