# Generated by Django 3.2.11 on 2022-05-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0007_diaobject_simversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaObjectTrut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaObjectId', models.BigIntegerField()),
                ('sim_searcheff_mask', models.IntegerField()),
                ('gentype', models.IntegerField()),
                ('non1a_index', models.IntegerField()),
                ('zcmb', models.FloatField()),
                ('zhelio', models.FloatField()),
                ('zcmb_shear', models.FloatField()),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('mwebv', models.FloatField()),
                ('galid', models.BigIntegerField()),
                ('galzphot', models.FloatField()),
                ('galzphoterr', models.FloatField()),
                ('rv', models.FloatField()),
                ('av', models.FloatField()),
                ('mu', models.FloatField()),
                ('lensedmu', models.FloatField()),
                ('peakmjd', models.FloatField()),
                ('mjd_trigger', models.FloatField()),
                ('peakmag_u', models.FloatField()),
                ('peakmag_g', models.FloatField()),
                ('peakmag_r', models.FloatField()),
                ('peakmag_i', models.FloatField()),
                ('peakmag_z', models.FloatField()),
                ('peakmag_Y', models.FloatField()),
                ('snrmax', models.FloatField()),
                ('snrmax2', models.FloatField()),
                ('snrmax3', models.FloatField()),
                ('nobs', models.IntegerField()),
                ('nobs_saturate', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_z',
            new_name='hostgal2_zphot',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_z_err',
            new_name='hostgal2_zphot_err',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q10',
            new_name='hostgal2_zphot_q010',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q20',
            new_name='hostgal2_zphot_q020',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q30',
            new_name='hostgal2_zphot_q030',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q40',
            new_name='hostgal2_zphot_q040',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q50',
            new_name='hostgal2_zphot_q050',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q60',
            new_name='hostgal2_zphot_q060',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q70',
            new_name='hostgal2_zphot_q070',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q80',
            new_name='hostgal2_zphot_q080',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q90',
            new_name='hostgal2_zphot_q090',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal2_zphot_q99',
            new_name='hostgal2_zphot_q100',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_z_err',
            new_name='hostgal_zpec_err',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q10',
            new_name='hostgal_zphot_q010',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q20',
            new_name='hostgal_zphot_q020',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q30',
            new_name='hostgal_zphot_q030',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q40',
            new_name='hostgal_zphot_q040',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q50',
            new_name='hostgal_zphot_q050',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q60',
            new_name='hostgal_zphot_q060',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q70',
            new_name='hostgal_zphot_q070',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q80',
            new_name='hostgal_zphot_q080',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q90',
            new_name='hostgal_zphot_q090',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_zphot_q99',
            new_name='hostgal_zphot_q100',
        ),
        migrations.RenameField(
            model_name='diaobject',
            old_name='hostgal_z',
            new_name='hostgal_zspec',
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal2_zphot_q000',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal2_zspec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal2_zspec_err',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal_zphot',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal_zphot_err',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal_zphot_p50',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diaobject',
            name='hostgal_zphot_q000',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokerName'], name='elasticc_br_brokerN_86cc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerclassifier',
            index=models.Index(fields=['brokerName', 'brokerVersion'], name='elasticc_br_brokerN_eb7553_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['topicName', 'streamMessageId'], name='elasticc_br_topicNa_73f5a4_idx'),
        ),
    ]
