# Generated by Django 3.2.11 on 2022-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0011_auto_20220617_1546'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diatruth',
            name='elasticc_di_diaSour_db8f99_idx',
        ),
        migrations.RemoveIndex(
            model_name='diatruth',
            name='elasticc_di_diaObje_f52792_idx',
        ),
        migrations.AlterField(
            model_name='diaobjecttruth',
            name='diaObjectId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diatruth',
            name='diaObjectId',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
