# Generated by Django 3.2.11 on 2022-06-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0013_mjd_in_truth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaobjecttruth',
            old_name='galsnep',
            new_name='galsnsep',
        ),
    ]
