# Generated by Django 3.2.11 on 2022-06-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0015_objecttruth_lensdmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaobjecttruth',
            name='diaObjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elasticc.diaobject'),
        ),
    ]
