# Generated by Django 4.0.6 on 2022-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0016_alter_diaobjecttruth_diaobjectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaobjecttruth',
            old_name='diaObjectId',
            new_name='diaObject',
        ),
        migrations.AlterField(
            model_name='diaobjecttruth',
            name='gentype',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='diaobjecttruth',
            name='sim_template_index',
            field=models.IntegerField(db_index=True),
        ),
    ]
