# Generated by Django 4.0.6 on 2022-08-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0026_diaalert_alertsenttimetamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaalert',
            old_name='alertSentTimetamp',
            new_name='alertSentTimestamp',
        ),
    ]
