# Generated by Django 4.0.6 on 2022-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0027_rename_alertsenttimetamp_diaalert_alertsenttimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassIdOfGentype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gentype', models.IntegerField(db_index=True)),
                ('classId', models.IntegerField(db_index=True)),
                ('exactmatch', models.BooleanField()),
                ('categorymatch', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ClassificationMap',
            new_name='GentypeOfClassId',
        ),
    ]
