# Generated by Django 4.0.6 on 2022-08-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0030_view_sourceclassifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaobjecttruth',
            name='diaObject',
            field=models.OneToOneField(db_column='diaObjectId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elasticc.diaobject'),
        ),
    ]
