# Generated by Django 4.0.6 on 2022-08-19 17:34

import math
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticc', '0040_probmetrics_matview'),
    ]

    operations = [
        migrations.RunSQL( f"""
CREATE MATERIALIZED VIEW elasticc_view_classifications_totprobpersource AS
  SELECT "classifierId","diaSourceId",SUM(probability) AS totprob
  FROM
  ( SELECT c."classifierId",m."diaSourceId",c.probability
    FROM elasticc_brokerclassification c
    INNER JOIN elasticc_brokermessage m ON c."brokerMessageId"=m."brokerMessageId"
  ) subq
  GROUP BY "classifierId","diaSourceId"
""" ),
        migrations.RunSQL( "GRANT SELECT ON elasticc_view_classifications_totprobpersource TO postgres_elasticc_admin_ro" )
    ]
