---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastdbdev-mongodb
  namespace: desc-tom-buckley-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-fastdbdev-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "70268"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,92576,95089,96414
        nersc.gov/roles: user
        nersc.gov/uid: "56805"
        nersc.gov/username: buckley
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-fastdbdev-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_EXTRA_USERNAMES
          value: mongodb_alert_writer
        - name: MONGODB_EXTRA_DATABASES
          value: alerts
        - name: MONGODB_EXTRA_PASSWORDS
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb-passwords
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin_passwd
        securityContext:
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 56805
        ports:
        - name: mongodb
          containerPort: 27017
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mongodb-data
          name: mongodb-datadir
        terminationMessagePolicy: File
        image:registry.nersc.gov/m1727/buckley/tom-mongodb:latest
      volumes:
      - name: mongodb-datadir
        persistentVolumeClaim:
          claimName: fastdbdev-mongodb-pvc