---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-query-runner
  namespace: desc-tom-buckley-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-query-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: 70268,99896
        nersc.gov/gid: "95089"
        nersc.gov/gids: 95089,57177,60152,96414
        nersc.gov/roles: user
        nersc.gov/uid: "56805"
        nersc.gov/username: buckley
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-query-runner
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: tom-postgres
        - name: DB_NAME
          value: tom_desc
        - name: DB_PASS
          value: fragile
        - name: DB_USER
          value: postgres
        image: registry.nersc.gov/m1727/buckley/devuan-chimaera-buckley:latest
        imagePullPolicy: Always
        name: tom-query-runner
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 56805
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: tom-secrets
        - mountPath: /tom_desc
          name: tom-deployment
        - mountPath: /query_results
          name: tom-query-results
        - mountPath: /code
          name: tom-checkout
        command: [ 'python' ]
        args: [ 'manage.py', 'long_query_runner', '-l' ]
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 57177
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: tom-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: tom-secrets
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/tom_desc_fastdb_dev
          type: Directory
        name: tom-checkout
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/tom_desc_fastdb_dev/tom_desc
          type: Directory
        name: tom-deployment
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/production/query_results
          type: Directory
        name: tom-query-results
---
apiVersion: v1
kind: Service
metadata:
  name: tom-query-runner
  namespace: desc-tom-buckley-dev
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-query-runner
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
