---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-app
  name: tom-app
  namespace: desc-tom-buckley-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-app
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: tom-postgres
        - name: DB_NAME
          value: tom_desc
        - name: DB_PASS
          value: fragile
        - name: DB_USER
          value: postgres
        - name: MONGODB_ADMIN
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_admin_passwd
        - name: MONGODB_ALERT_WRITER
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_writer
        - name: MONGODB_ALERT_WRITER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_writer_password
        - name: MONGODB_ALERT_READER
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_reader
        - name: MONGODB_ALERT_READER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tom-secrets
              key: mongodb_alert_reader_password
        image: registry.nersc.gov/m1727/buckley/devuan-chimaera-buckley:latest
        imagePullPolicy: Always
        name: tom-app
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 56805
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: tom-secrets
        - mountPath: /tom_desc
          name: tom-deployment
        - mountPath: /code
          name: tom-checkout
        - mountPath: /sample
          name: tom-sample
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 57177
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: tom-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: tom-secrets
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/tom_desc_fastdb_dev
          type: Directory
        name: tom-checkout
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/tom_deployment/tom_desc_fastdb_dev/tom_desc
          type: Directory
        name: tom-deployment
      - hostPath:
          path: /global/cfs/cdirs/desc-td/ELASTICC2
          type: Directory
        name: tom-sample
---
apiVersion: v1
kind: Service
metadata:
  name: tom-app
  namespace: desc-tom-buckley-dev
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tom-app-ingress
  namespace: desc-tom-buckley-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-desc-tom-buckley-dev-tom-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tom-app
  namespace: desc-tom-buckley-dev
spec:
  rules:
  - host: tom-app.desc-tom-buckley-dev.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: tom-app-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: desc-tom-fastdb-dev.lbl.gov 
    http:
      paths:
      - backend:
          service:
            name: tom-app-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - desc-tom-fastdb-dev.lbl.gov
    - tom-app.desc-tom-buckley-dev.production.svc.spin.nersc.org
    secretName: tom-cert
---
